# Generated by Django 4.1.1 on 2022-09-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_CRUD', '0002_alter_restaurant_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four')], default='Zero'),
        ),
    ]
