# Generated by Django 4.1.1 on 2022-09-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_CRUD', '0003_alter_restaurant_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField()),
                ('avg', models.FloatField()),
                ('std', models.FloatField()),
            ],
        ),
    ]
